### ISSUE TITLE
Error when trying to display editor

### ISSUE THREAD

**Issue by miloskroulik** [Gisto/Gisto#147]
When I try to add new Gist, I encounter following error (as displayed in command line):
````
[7630:0223/141233:INFO:CONSOLE(6272)] ""TypeError: Cannot read property 'appendChild' of null\n    at new s (eval at \u003Canonymous\u003E (file:///tmp/.org.chromium.Chromium.psZF5v/js/gisto.min.js:1:0), \u003Canonymous\u003E:1:315)\n    at file:///tmp/.org.chromium.Chromium.psZF5v/js/gisto.min.js:12525:41\n    at file:///tmp/.org.chromium.Chromium.psZF5v/js/gisto.min.js:6303:399\n    at e (file:///tmp/.org.chromium.Chromium.psZF5v/js/gisto.min.js:6217:497)\n    at file:///tmp/.org.chromium.Chromium.psZF5v/js/gisto.min.js:6221:235\n    at a.bugsnag (http://d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js:1:160)\n    at http://d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js:1:5070"", source: file:///tmp/.org.chromium.Chromium.psZF5v/js/gisto.min.js (6272)
[7630:0223/141233:INFO:CONSOLE(6272)] ""TypeError"", source: file:///tmp/.org.chromium.Chromium.psZF5v/js/gisto.min.js (6272
````

I'm using latest Gisto on Ubuntu 14.04. Enclosed screenshot shows user interface of gist add disalog.
![screen_024](https://cloud.githubusercontent.com/assets/1777307/6328450/e5bcfa5e-bb67-11e4-8eb5-ea04cb3d56df.png)

**Comment by morsdyce** [comment]
@miloskroulik The issue should be resolved now, will very much appreciate if you could try the latest nightly build and see if it works.

**Comment by miloskroulik** [comment]
I tried the latest build (linux-64 from http://build.gistoapp.com/20150301/) but the error looks the same:

````
[9817:0302/111927:INFO:CONSOLE(6272)] ""TypeError: Cannot read property 'appendChild' of null\n    at new s (eval at \u003Canonymous\u003E (file:///tmp/.org.chromium.Chromium.dZVTMe/js/gisto.min.js:1:0), \u003Canonymous\u003E:1:315)\n    at file:///tmp/.org.chromium.Chromium.dZVTMe/js/gisto.min.js:12389:41\n    at file:///tmp/.org.chromium.Chromium.dZVTMe/js/gisto.min.js:6303:399\n    at e (file:///tmp/.org.chromium.Chromium.dZVTMe/js/gisto.min.js:6217:497)\n    at file:///tmp/.org.chromium.Chromium.dZVTMe/js/gisto.min.js:6221:235\n    at a.bugsnag (http://d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js:1:160)\n    at http://d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js:1:5070"", source: file:///tmp/.org.chromium.Chromium.dZVTMe/js/gisto.min.js (6272)
[9817:0302/111927:INFO:CONSOLE(6272)] ""TypeError"", source: file:///tmp/.org.chromium.Chromium.dZVTMe/js/gisto.min.js (6272)
````

**Comment by sanusart** [comment]
Hey @miloskroulik 
You can try to remove Gisto directory at `~/.config/gisto` and re-run the program. Maybe some files got corupted somehow.

**Comment by miloskroulik** [comment]
Thanks @sanusart it works nicely.

**Comment by miloskroulik** [comment]
The problem is back as soon as I change some settings and click on update. Please reopen the issue, as it's still very much present.

**Comment by sanusart** [comment]
Any chance you running Ubuntu as virtual machine?

On Friday, March 6, 2015, Miloš Kroulík <notifications@github.com> wrote:

> The problem is back as soon as I change some settings and click on update.
> Please reopen the issue, as it's still very much present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gisto/Gisto/issues/147#issuecomment-77520992>.
>


-- 
------------------------------

*SASHA KHAMKOV*
*web developer*
www.sanusart.com | sanusart@gmail.com | +972 (0) 54 7450 672
------------------------------

Facebook <http://www.facebook.com/sanusart>  Twitter
<http://twitter.com/sanusart>  *Linked*in
<http://www.linkedin.com/in/sanusart>  Google+
<https://plus.google.com/111862979601357461785>  GitHub
<http://github.com/sanusart/>

**Comment by miloskroulik** [comment]
No, I'm running Linux Mint 17.1 Cinnamon

**Comment by sanusart** [comment]
Ok. Will try to reproduce this bug.
Another question just to be sure: Do you have official Gisto release installed also alongside the nightly?

**Comment by miloskroulik** [comment]
No, I'm trying just the dev version. Today, I updated to the latest nightly build before reporting the problem with settings.

**Comment by sanusart** [comment]
Du you have `gconf` package installed? If not this may explain settings
read/write issues?

On Friday, March 6, 2015, Miloš Kroulík <notifications@github.com> wrote:

> No, I'm trying just the dev version. Today, I updated to the latest
> nightly build before reporting the problem with settings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gisto/Gisto/issues/147#issuecomment-77548934>.
>


-- 
------------------------------

*SASHA KHAMKOV*
*web developer*
www.sanusart.com | sanusart@gmail.com | +972 (0) 54 7450 672
------------------------------

Facebook <http://www.facebook.com/sanusart>  Twitter
<http://twitter.com/sanusart>  *Linked*in
<http://www.linkedin.com/in/sanusart>  Google+
<https://plus.google.com/111862979601357461785>  GitHub
<http://github.com/sanusart/>

**Comment by morsdyce** [comment]
Hi @miloskroulik 
We managed to reproduce the issue, it was related to the status bar required element was not being rendered. 

Please check the latest nightly and confirm if it is fixed for you.
Thanks!

**Comment by miloskroulik** [comment]
Yes, it seems to be fixed. Thanks a lot for your attention to my problem (which is understandably often missing in some other OSS communities).

**Comment by morsdyce** [comment]
We're just excited that people like and use Gisto and want to give them the best experience we can with our limited resources :)

You helped us find a bug that might have been uncaught in a release so we thank you for taking your time and helping us figure this out.
